export const API_ERROR_CODES = {
	authMissingToken: "AUTH_MISSING_TOKEN",
	authInvalidToken: "AUTH_INVALID_TOKEN",
	authForbidden: "AUTH_FORBIDDEN",
	authStoreScopeViolation: "AUTH_STORE_SCOPE_VIOLATION",
	authIdentityConflict: "AUTH_IDENTITY_CONFLICT",
	deviceBootstrapInvalid: "DEVICE_BOOTSTRAP_INVALID",
	deviceSignatureMissing: "DEVICE_SIGNATURE_MISSING",
	deviceSignatureInvalid: "DEVICE_SIGNATURE_INVALID",
	deviceNotFound: "DEVICE_NOT_FOUND",
	deviceNotActive: "DEVICE_NOT_ACTIVE",
	deviceClockSkew: "DEVICE_CLOCK_SKEW",
	tryOnSessionNotFound: "TRY_ON_SESSION_NOT_FOUND",
	tryOnSessionExpired: "TRY_ON_SESSION_EXPIRED",
	tryOnSessionAlreadyBound: "TRY_ON_SESSION_ALREADY_BOUND",
	tryOnInvalidStatus: "TRY_ON_INVALID_STATUS",
	tryOnProductNotFound: "TRY_ON_PRODUCT_NOT_FOUND",
	mediaAuthRequired: "MEDIA_AUTH_REQUIRED",
	mediaSessionNotAuthorized: "MEDIA_SESSION_NOT_AUTHORIZED",
	mediaInvalidScope: "MEDIA_INVALID_SCOPE",
	mediaExpired: "MEDIA_EXPIRED",
	mediaStorageKeyInvalid: "MEDIA_STORAGE_KEY_INVALID",
	couponTemplateNotFound: "COUPON_TEMPLATE_NOT_FOUND",
	couponAlreadyClaimed: "COUPON_ALREADY_CLAIMED",
	couponNotFound: "COUPON_NOT_FOUND",
	couponExpired: "COUPON_EXPIRED",
	couponAlreadyRedeemed: "COUPON_ALREADY_REDEEMED",
	couponInvalidStatus: "COUPON_INVALID_STATUS",
	idempotencyKeyMissing: "IDEMPOTENCY_KEY_MISSING",
	idempotencyReplay: "IDEMPOTENCY_REPLAY",
	idempotencyConflict: "IDEMPOTENCY_CONFLICT",
	validationFailed: "VALIDATION_FAILED",
	resourceNotFound: "RESOURCE_NOT_FOUND",
	rateLimited: "RATE_LIMITED",
	internalError: "INTERNAL_ERROR",
	serviceUnavailable: "SERVICE_UNAVAILABLE",
} as const;

export type ApiErrorCode =
	(typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
